# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TestBicepJob
    jobs:
    - job: TestBicepFile
      displayName:  Testcases
      pool:
        vmImage: ubuntu-latest
      steps:
         - task: RunARMTTKTests@1
           inputs:
              templatelocation: '$(System.DefaultWorkingDirectory)\BicepSolution'
              resultLocation: '$(System.DefaultWorkingDirectory)\results'
              allTemplatesMain: false
              cliOutputResults: true
         - task: PublishTestResults@2
           inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
           
  - stage: DeployBicep
    displayName: Deploy Bicep Stage
    jobs:
       - job: waitforvalidation
         displayName: Wait for validation
         timeoutInMinutes: 4200
         steps:
           - task: ManualValidation@0
             timeoutInMinutes: 1400
             inputs:
               notifyUsers: prayanka.gochipatula@valuemomentum.com
               instructions: "New build triggered, please validate $(Build.BuildId)"
               onTimeout: resume

       - job: deploytoazure
         displayName: Deploytoazure
         pool:
          vmImage: ubuntu-latest
         dependsOn: waitforvalidation
         variables:
              Resource-Group: 'BicepPoc'
              location: 'eastus'

         steps:
            - task: AzureCLI@2
              displayName: 'Azure CLI '
              inputs:
                azureSubscription: 'Pay-As-You-Go (a33c45cf-25ce-42d7-910b-5a0b8c55dd32)'
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name $(Resource-Group) --location $(location)
                  az deployment group create `
                    --resource-group $(Resource-Group) `
                    --template-file main.bicep
                workingDirectory: '$(System.DefaultWorkingDirectory)/_BicepPoc-CI/drop'