# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:  
  - stage: DeployBicep
    displayName: Deploy Bicep Stage
    jobs:
       - job: deploytoazure
         displayName: Deploytoazure
         variables:
              Resource-Group: 'bicepdata'
              location: 'eastus'

         steps:
            - task: AzureCLI@2
              displayName: 'Azure CLI '
              inputs:
                azureSubscription: 'Pay-As-You-Go (a33c45cf-25ce-42d7-910b-5a0b8c55dd32)'
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name $(Resource-Group) --location $(location)
                  az deployment group create `
                    --resource-group $(Resource-Group) `
                    --template-file main.bicep
                workingDirectory: '$(System.DefaultWorkingDirectory)/bicepsolution/'